{% set name = "pixi" %}
{% set version = "0.76.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prefix-dev/pixi/releases/download/v{{ version }}/source.tar.gz
  sha256: dee0c22ee232f070c9481142b4c60c57f5acf5987b675c82b824a7636b2b9767

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - pkg-config
    - cmake
    - make  # [unix]
    - git
  host:
    - openssl {{ openssl }} # [linux]

test:
  commands:
    - pixi --help
    - test -f $PREFIX/share/bash-completion/completions/pixi # [unix]
    - test -f $PREFIX/share/zsh/site-functions/_pixi # [unix]
    - test -f $PREFIX/share/fish/vendor_completions.d/pixi.fish # [unix]
    - PIXI_HOME=$(mktemp -d) pixi init . && grep repo.anaconda.com/pkgs/main pixi.toml  # [unix]
    - set PIXI_HOME=%TEMP%\pixi-ph & mkdir %PIXI_HOME% 2>nul & pixi init . & findstr repo.anaconda.com/pkgs/main pixi.toml  # [win]

about:
  home: https://github.com/prefix-dev/pixi
  dev_url: https://github.com/prefix-dev/pixi
  doc_url: https://pixi.prefix.dev
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
  description: |
    pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.

    pixi provides all developers the exceptional experience that is usually found with package managers like cargo or yarn but for any language.

    # Highlights

    - Support for multiple languages like Python, C++ and R using Conda packages
    - All OS's: Linux, Windows, macOS (including Apple Silicon)
    - A lockfile is always included and always up-to-date.
    - A clean and simple Cargo-like command-line interface.
    - Install tools per-project or system-wide.
    - Completely written in Rust and build on top of the rattler library.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  license_family: BSD

